FROM ubuntu:18.04

#FROM ubuntu:16.04

WORKDIR /app

COPY . /app


# install python and flask
RUN apt-get update && apt-get install -y python3-pip python3-dev && pip3 install flask

# install nodejs in ubuntu
RUN apt-get install -y nodejs

# install tesseract-ocr
RUN apt-get install -y tesseract-ocr

# pip install pytesseract opencv-python numpy
# RUN pip3 install --upgrade setuptools
RUN python3 -m pip install -U pip
RUN python3 -m pip install -U setuptools
RUN pip3 install pytesseract opencv-python numpy

COPY node-service/package*.json ./node-service

# install npm
RUN apt-get install -y npm

RUN npm install

COPY . .

EXPOSE 3000
EXPOSE 5000

RUN chmod 777 script.sh

# run node-service/index.js and python-service/app.py
CMD ["./script.sh"]