version: "3.9"
services:
  node-service:
    build: ./node-service
    ports:
      - "8080:8080"
  python-service:
    build: ./python-service
    ports:
      - "5000:5000"
  # mssql-service:
  #   build: ./mssql-service
  #   ports:
  #     - "1401:1433"
  #   volumes:
  #     - "./sql1data:/var/opt/mssql"
